[package]
name = "molecule"
version = "0.1.0"
authors = ["zc62"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
web-sys = "0.3"

[profile.release]
opt-level = "s"
lto = true
